name: NewsCI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
        uses : actions/checkout@v1

      - name: Remove package-lock
        run : rm package-lock.json
        
      - name: Install node/modules
        run : npm install

      - name: List files
        run : ls -la
        
      - name: Build the project
        run : npm run generate

      - name: Send all materials
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          password: ${{ secrets.PASSWORD_SERVER }}
          port: "22"
          source: "distNews"
          target: "/var/www/html"
